// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDu5AK-MikeBLQmFRbw7XYFlMlf5FD-qNU',
    appId: '1:471314318797:web:1bb831623fb08932f3f084',
    messagingSenderId: '471314318797',
    projectId: 'art-in-you',
    authDomain: 'art-in-you.firebaseapp.com',
    storageBucket: 'art-in-you.appspot.com',
    measurementId: 'G-0ERTZPVSL7',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBv9LaVjEUWVIGky5TFuKLG18lEuVG_U8o',
    appId: '1:471314318797:android:996a56c93e7138a1f3f084',
    messagingSenderId: '471314318797',
    projectId: 'art-in-you',
    storageBucket: 'art-in-you.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD6BxIzpJBlTjiyRY6cOsnXInTpYzFgdyU',
    appId: '1:471314318797:ios:0f2ac78f47569b3bf3f084',
    messagingSenderId: '471314318797',
    projectId: 'art-in-you',
    storageBucket: 'art-in-you.appspot.com',
    androidClientId: '471314318797-s78rabvm679qcr446d40qa03ve08q3jq.apps.googleusercontent.com',
    iosClientId: '471314318797-kg0c7u4tud7firlb6glpt31fv92g2a67.apps.googleusercontent.com',
    iosBundleId: 'com.artinyou.artInyou',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyD6BxIzpJBlTjiyRY6cOsnXInTpYzFgdyU',
    appId: '1:471314318797:ios:13315e49b7fea463f3f084',
    messagingSenderId: '471314318797',
    projectId: 'art-in-you',
    storageBucket: 'art-in-you.appspot.com',
    androidClientId: '471314318797-s78rabvm679qcr446d40qa03ve08q3jq.apps.googleusercontent.com',
    iosClientId: '471314318797-9bd2j98eei8jkaq7h0usi0m8jc39qutd.apps.googleusercontent.com',
    iosBundleId: 'com.artinyou.artInyou.RunnerTests',
  );
}
